/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GenerationSettings {
  'decimalPrecision' : bigint,
  'integerOnly' : boolean,
  'quantity' : bigint,
  'fractionMode' : boolean,
}
export interface Session {
  'id' : SessionId,
  'user' : Principal,
  'variants' : Array<Variant>,
  'settings' : GenerationSettings,
  'timestamp' : bigint,
  'originalQuestion' : string,
}
export type SessionId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Variant {
  'correctOption' : string,
  'questionText' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countSessions' : ActorMethod<[], bigint>,
  'deleteSession' : ActorMethod<[SessionId], undefined>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSession' : ActorMethod<[SessionId], Session>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSession' : ActorMethod<
    [SessionId, string, GenerationSettings, Array<Variant>],
    SessionId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];