/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionId = IDL.Text;
export const Variant = IDL.Record({
  'correctOption' : IDL.Text,
  'questionText' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
});
export const GenerationSettings = IDL.Record({
  'decimalPrecision' : IDL.Nat,
  'integerOnly' : IDL.Bool,
  'quantity' : IDL.Nat,
  'fractionMode' : IDL.Bool,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'user' : IDL.Principal,
  'variants' : IDL.Vec(Variant),
  'settings' : GenerationSettings,
  'timestamp' : IDL.Int,
  'originalQuestion' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countSessions' : IDL.Func([], [IDL.Nat], ['query']),
  'deleteSession' : IDL.Func([SessionId], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSession' : IDL.Func([SessionId], [Session], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSession' : IDL.Func(
      [SessionId, IDL.Text, GenerationSettings, IDL.Vec(Variant)],
      [SessionId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionId = IDL.Text;
  const Variant = IDL.Record({
    'correctOption' : IDL.Text,
    'questionText' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
  });
  const GenerationSettings = IDL.Record({
    'decimalPrecision' : IDL.Nat,
    'integerOnly' : IDL.Bool,
    'quantity' : IDL.Nat,
    'fractionMode' : IDL.Bool,
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'user' : IDL.Principal,
    'variants' : IDL.Vec(Variant),
    'settings' : GenerationSettings,
    'timestamp' : IDL.Int,
    'originalQuestion' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countSessions' : IDL.Func([], [IDL.Nat], ['query']),
    'deleteSession' : IDL.Func([SessionId], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSession' : IDL.Func([SessionId], [Session], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSession' : IDL.Func(
        [SessionId, IDL.Text, GenerationSettings, IDL.Vec(Variant)],
        [SessionId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };